from projects.ewoodx.config.workspace import (
    EWOODX_PROJECT_ROOT,
    EWOODX_REPOSITORY_ROOT,
    EWOODX_WORKSPACE_LAYOUT,    
    SENSING_DOMAIN,
    DESIGN_DOMAIN,
    ROBOT_CONTROL_DOMAIN,
    ENTRY_NAME_PREFIX,
    ENTRY_DATE_FORMAT,
)

from projects.ewoodx.config.sensing import (
    CALIBRATION_ROOT,
    TABLE_HEIGHT_MM,
    TABLE_WIDTH_MM,
    

    ARDUCAM_CAMERA_INDEX,
    ARDUCAM_IMAGE_WIDTH,
    ARDUCAM_IMAGE_HEIGHT,
    ARDUCAM_CHECKERBOARD_INNER_CORNERS,
    ARDUCAM_CHECKERBOARD_SQUARE_SIZE_MM,
    ARDUCAM_CALIBRATION_LAYOUT,
    ARDUCAM_ARUCO_DICTIONARY,
    ARDUCAM_MARKER_SIZE_MM,
    ARDUCAM_MARKER_WORLD_POSITIONS_MM,
    ARDUCAM_MARKER_OUTER_CORNERS,
    ARDUCAM_CAMERA_HEIGHT_MM,

    ANGETUBE_CAMERA_INDEX,
    ANGETUBE_IMAGE_WIDTH,
    ANGETUBE_IMAGE_HEIGHT,
    ANGETUBE_CAMERA_FPS,
    ANGETUBE_CAMERA_FOURCC,

    ANGETUBE_FOCUS_MODE,
    ANGETUBE_FOCUS_VALUE,
    ANGETUBE_EXPOSURE_MODE,
    ANGETUBE_EXPOSURE_VALUE,
    ANGETUBE_BRIGHTNESS,
    ANGETUBE_CONTRAST,
    ANGETUBE_SATURATION,
    ANGETUBE_SHARPNESS,
    ANGETUBE_GAIN,
    ANGETUBE_BACKLIGHT_COMPENSATION,
    ANGETUBE_WHITE_BALANCE_MODE,
    ANGETUBE_WHITE_BALANCE_TEMPERATURE,
    ANGETUBE_DIGITAL_ZOOM,

    ANGETUBE_CHECKERBOARD_INNER_CORNERS,
    ANGETUBE_CHECKERBOARD_SQUARE_SIZE_MM,
    ANGETUBE_CALIBRATION_MODEL,
    ANGETUBE_FISHEYE_BALANCE,
    ANGETUBE_FISHEYE_FOV_SCALE,
    ANGETUBE_FISHEYE_CHECK_COND,
    ANGETUBE_FISHEYE_RECOMPUTE_EXTRINSIC,
    ANGETUBE_FISHEYE_FIX_SKEW,

    ANGETUBE_CALIBRATION_LAYOUT,
    ANGETUBE_ARUCO_DICTIONARY,
    ANGETUBE_MARKER_SIZE_MM,
    ANGETUBE_MARKER_WORLD_POSITIONS_MM,
    ANGETUBE_MARKER_OUTER_CORNERS,
    ANGETUBE_CAMERA_HEIGHT_MM,

    TIMBER_MIN_CONTOUR_AREA_PX,
    TIMBER_CONTOUR_APPROX_FACTOR,
    TIMBER_THICKNESS_MM,
)

from projects.ewoodx.config.entity import (
    TIMBER_ENTITY_TYPE,
    TIMBER_ID_PREFIX,
    ENTITY_ID_SEQUENCE_MIN_WIDTH,
    ENTITY_ID_SEQUENCE_MAX_VALUE,
    ENTITY_ID_RANDOM_LENGTH,
    ENTITY_ID_RANDOM_ALPHABET,
    TIMBER_ENTITY_INDEX,
)

from projects.ewoodx.config.communication import (
    AGENTS_RUNTIME_ROOT,
    MASTER_BIND_HOST,
    MASTER_HOST,
    MASTER_PORT,
    SENSING_AGENT_ID,
    SENSING_AGENT_ROLES,
    SENSING_AGENT_HOST,
    SENSING_AGENT_PORT,
    SENSING_AGENT_POLL_INTERVAL,
)

from projects.ewoodx.config.projection import (
    PROJECTOR_CALIBRATION_LAYOUT,

    PROJECTOR_HEIGHT_MM,
    PROJECTOR_POS_X_MM,
    PROJECTOR_POS_Y_MM,

    PROJECTOR_WIDTH,
    PROJECTOR_HEIGHT,
    PROJECTOR_SCREEN_ORIGIN_X,
    PROJECTOR_SCREEN_ORIGIN_Y,

    PROJECTOR_OFFSET_X_MM,
    PROJECTOR_OFFSET_Y_MM,

    PROJECTOR_CALIBRATION_MODE,
)


__all__ = [
    "EWOODX_PROJECT_ROOT",
    "EWOODX_REPOSITORY_ROOT",
    "EWOODX_WORKSPACE_LAYOUT",    
    "SENSING_DOMAIN",
    "DESIGN_DOMAIN",
    "ROBOT_CONTROL_DOMAIN",
    "ENTRY_NAME_PREFIX",
    "ENTRY_DATE_FORMAT",

    "CALIBRATION_ROOT",
    "TABLE_HEIGHT_MM",
    "TABLE_WIDTH_MM",

    "ARDUCAM_CAMERA_INDEX",
    "ARDUCAM_IMAGE_WIDTH",
    "ARDUCAM_IMAGE_HEIGHT",
    "ARDUCAM_CHECKERBOARD_INNER_CORNERS",
    "ARDUCAM_CHECKERBOARD_SQUARE_SIZE_MM",
    "ARDUCAM_CALIBRATION_LAYOUT",
    "ARDUCAM_ARUCO_DICTIONARY",
    "ARDUCAM_MARKER_SIZE_MM",
    "ARDUCAM_MARKER_WORLD_POSITIONS_MM",
    "ARDUCAM_MARKER_OUTER_CORNERS",
    "ARDUCAM_CAMERA_HEIGHT_MM",

    "ANGETUBE_CAMERA_INDEX",
    "ANGETUBE_IMAGE_WIDTH",
    "ANGETUBE_IMAGE_HEIGHT",
    "ANGETUBE_CAMERA_FPS",
    "ANGETUBE_CAMERA_FOURCC",

    "ANGETUBE_FOCUS_MODE",
    "ANGETUBE_FOCUS_VALUE",
    "ANGETUBE_EXPOSURE_MODE",
    "ANGETUBE_EXPOSURE_VALUE",
    "ANGETUBE_BRIGHTNESS",
    "ANGETUBE_CONTRAST",
    "ANGETUBE_SATURATION",
    "ANGETUBE_SHARPNESS",
    "ANGETUBE_GAIN",
    "ANGETUBE_BACKLIGHT_COMPENSATION",
    "ANGETUBE_WHITE_BALANCE_MODE",
    "ANGETUBE_WHITE_BALANCE_TEMPERATURE",
    "ANGETUBE_DIGITAL_ZOOM",

    "ANGETUBE_CHECKERBOARD_INNER_CORNERS",
    "ANGETUBE_CHECKERBOARD_SQUARE_SIZE_MM",
    "ANGETUBE_CALIBRATION_MODEL",
    "ANGETUBE_FISHEYE_BALANCE",
    "ANGETUBE_FISHEYE_FOV_SCALE",
    "ANGETUBE_FISHEYE_CHECK_COND",
    "ANGETUBE_FISHEYE_RECOMPUTE_EXTRINSIC",
    "ANGETUBE_FISHEYE_FIX_SKEW",

    "ANGETUBE_CALIBRATION_LAYOUT",
    "ANGETUBE_ARUCO_DICTIONARY",
    "ANGETUBE_MARKER_SIZE_MM",
    "ANGETUBE_MARKER_WORLD_POSITIONS_MM",
    "ANGETUBE_MARKER_OUTER_CORNERS",
    "ANGETUBE_CAMERA_HEIGHT_MM",    

    "TIMBER_MIN_CONTOUR_AREA_PX",
    "TIMBER_CONTOUR_APPROX_FACTOR",
    "TIMBER_THICKNESS_MM",

    "TIMBER_ENTITY_TYPE",
    "TIMBER_ID_PREFIX",
    "ENTITY_ID_SEQUENCE_MIN_WIDTH",
    "ENTITY_ID_SEQUENCE_MAX_VALUE",
    "ENTITY_ID_RANDOM_LENGTH",
    "ENTITY_ID_RANDOM_ALPHABET",
    "TIMBER_ENTITY_INDEX",

    "AGENTS_RUNTIME_ROOT",
    "MASTER_BIND_HOST",
    "MASTER_HOST",
    "MASTER_PORT",
    "SENSING_AGENT_ID",
    "SENSING_AGENT_ROLES",
    "SENSING_AGENT_HOST",
    "SENSING_AGENT_PORT",
    "SENSING_AGENT_POLL_INTERVAL",

    "PROJECTOR_CALIBRATION_LAYOUT",

    "PROJECTOR_HEIGHT_MM",
    "PROJECTOR_POS_X_MM",
    "PROJECTOR_POS_Y_MM",

    "PROJECTOR_WIDTH",
    "PROJECTOR_HEIGHT",
    "PROJECTOR_SCREEN_ORIGIN_X",
    "PROJECTOR_SCREEN_ORIGIN_Y",

    "PROJECTOR_OFFSET_X_MM",
    "PROJECTOR_OFFSET_Y_MM",

    "PROJECTOR_CALIBRATION_MODE",
]